language: generic
script: echo hey
services:
  - docker
after_script:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  - docker container ls
  - docker pull alpine
  - docker run -it --memory="6g" alphine
  - docker stats --no-stream
