language: shell
matrix:
  include:
  - name: "Windows 10"
    os: windows
  - name: "Xenial GCC5"
    os: linux
    compiler: gcc
  - name: "Xenial LLVM7"
    os: linux
    compiler: clang
  - name: "Mojave"
    os: osx
    osx_image: xcode10.3
    env: MACOSX_DEPLOYMENT_TARGET=10.11
script: true
deploy:
- provider: releases
  api_key: $OAUTH_TOKEN
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
