jobs:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode12.2
      cache:
        yarn: true
      install:
        - yarn --production
        - brew tap phrase/brewed
        - brew install phrase
      script:
        - ls
