before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
jobs:
  include:
    - stage: test
      language: shell
      dist: bionic
      script: echo test
    - dist: xenial
      stage: deploy
      script: echo deploy
