sudo: required
dist: trusty

language: shell
jdk: oraclejdk8

addons:
  postgresql: 9.6

install:
  - sudo apt-get install -y postgresql-9.6-postgis-2.3
  - sudo service postgresql restart
before_script:
  - psql -c 'CREATE DATABASE "test";' -U postgres
  
script: true
