language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install -y postgresql-12 postgresql-client-12
before_script:
  - psql --version
  - ps -ef | grep postgres
  - psql -c 'create database travis_ci_test;' -U postgres
script: true
services:
  - postgresql
addons:
  postgresql: "12"
