dist: focal

language: ruby

rvm:
  - 2.7.2

cache:
- bundler

before_script:
- psql -c 'create database dnsimple_slack_test;' -U postgres
- bundle exec sequel -m db/migrations/ postgres://postgres:@localhost:5432/dnsimple_slack_test

script:
- bundle exec rubocop
- bundle exec rspec --tag ~real_api_calls

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
- postgresql

env:
  global:
    - PGPORT=5433
    - POSTGRES_URL="postgres://postgres:@localhost:5432/dnsimple_slack_test"
    - RACK_SESSION_COOKIE_SECRET="travis-ci-rack-session-cookie-secret"


