addons:
  apt:
    packages:
    - redis-server
jobs:
  include:
    - 
      dist: xenial
      script: redis-server --version
    -
      dist: trusty
      script: redis-server --version
    - 
      dist: focal
      script: redis-server --version
