---
os: linux
node_js: 12.13.0
language: node_js
dist: focal
cache:
  directories:
  - "~/.npm"
  - "~/npm"
services:
- postgresql
- redis
- rabbitmq
addons:
  postgresql: '12'
  apt:
    packages:
    - rabbitmq-server
    - postgresql-12
    - postgresql-client-12
    - postgresql-12-postgis-3
before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
install: true
env:
- PGUSER: travis
- PGPASSWORD: travis
- PGPORT: '5432'
- PGHOST: localhost
- DATABASE_URL: postgres://localhost:5432/testphinternal
- ENVIRONMENT: test
- FORCE_DB_SETUP: 'true'
- PHIN_LOGGER_FORCE_CONSOLE: 'false'
- SKIP_CONFIG_LIST: 'true'
