os: linux
language: ruby
dist: focal
ruby: 2.4.1
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - gem install bundler --no-document --version "$(grep -A 1 'BUNDLED WITH' Gemfile.lock | tail -n 1)"
  - bundle version
