language: generic
before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
services:
  - docker
script: true

dist: xenial
addons:
  apt:
    packages:
      - postgresql-11
  postgresql: '11'

services:
  - postgresql

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 11
  - postgres --version
before_script:
   - psql -c 'create database travis_ci_test_db;' -U postgres
