language: shell
dist: bionic

services:
  - postgresql
addons:
  postgresql: "9.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11  
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE {{db_name}};' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  #- cp config/database.yml.travis config/database.yml
