language: node_js
node_js: '12'
env:
- DEPLOY_DEST=staging
services:
- docker
branches:
  only:
  - master
  - elastic-7_6_1
  - "/^v[0-9].*$/"
script: true
deploy:
- provider: script
  skip_cleanup: true
  script: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$ && $DEPLOY_DEST == staging"
after_deploy:
- echo $TRAVIS_TAG
- echo $TRAVIS_BRANCH
notifications:
  slack:
    secure: VvqR1ZXpp1izBzEO6p090V0VeMF3VawHTyysP9BKhdxeSKZ9F16PrC1VclD0Zo9oO4qgA7FgnVPrVIuV6W6g74y085d4N3BDP+X2wNOeBJh/LrDXJeHijOtW5mW322KzYVEx2sU7oiDjureipRExMF6FlwLiPvxC+Q3eOAVoOCsqessGlpGWF/+QWdfDVGo/mqXGas9Hs1tWL740tv+1N84KqCVKqw0nCR4hL1BZRVwa6hOvxtrCi7pdnIVXYeXQimMzJ0mPoyBVHAvE3K2pxAB38dqYqId0PQZIDwpelJ87090ry1oyi41SGadsQz39lqd1VYmtIAew9p+t662Qj1xlFZgijZBWd8jSdfCjrdVUr/pPVxqvw2HvEcRCUce3HunZBsMDGVNSSwEXjuQIbRg16097M07cD7LOWy09ybr7wD9HElnYe4ltbVvBoaz+H65r43kzcUAPcc7lqLyZTXYBQl/EXUdwGIaitbabd1+pVfxv9gOuQW6/QRdubUX13Hb18G0MG3aOM7h7+PP0wvDMqYPt/XWK0oC02c2+5njW1MQiZ7Dft3YDmwAU721Bm0vdQRJynv4K9Um4MKyiC8lkwHKN3jvobKTuYHpIIe1pxsEsgmqxDnEXLj1hyx0Z9sfi7Q7PD6zDHgDkkwK7hTWMqwlr/7XuZs5e82EjZAs=
