---
os: linux
dist: focal
language: shell
install: true
script: true
deploy:
  - provider: script
    image: ruby:latest
    script:
      - gem install dpl && gem install faraday -v 1.8.0
      - dpl --provider=releases --api-key=$GH_AUTH_TOKEN --file=FILE.a
