---
os: linux
dist: xenial
language: python

install: true

script:
  - ./test.sh

after_script:
  - export VERSION="123"
  - echo $VERSION

deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    condition: $VERSION = 123
