language: node_js

script: true

after_success:
              - echo $TRAVIS_TEST_RESULT

jobs:
  include:
    - if: branch = test && type = push
      script: true
      deploy:
        provider: script
        cleanup: true
        on:
          branch: test
