---
language: node_js

node_js:
  - "10.23.0"

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
env:
  global:
    - PGPORT=5433
    - PGUSER=travis

before_install:
  - sudo sed -i -e "/local.*peer/s/postgres/all/" -e "s/peer\|md5/trust/g" /etc/postgresql/*/main/pg_hba.conf
  - postgres --version

before_script:
  - psql -Utravis -p5433 -c 'create database travis_ci_test;'
  - psql -p5433 -c "SELECT version();"

script: echo "default script"
