language: shell
install: echo main_install

jobs:
  include:
    - stage: test
      name: "CI Checks: Rubocop, Brakeman & Bundle Audit"
      install: echo hello1
    - stage: test2
      install: echo hello2
      name: "RSpec"
    - stage: deploy
      name: "Deploy"
