language: generic
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
services:
  - docker
install: true
script: echoc "tag testing"
jobs:
  include:
    - dist: bionic
    - dist: xenial
    - dist: trusty
