dist: bionic
env:
  global:
    - PGPORT=5433
    - PGUSER=travis

addons:
  apt:
    packages:
      - postgresql-11.8
  postgresql: '11.8'

before_install:
   - echo 'installing postgresql'
   - sudo sed -i 's/port = 5432 */port = 5433/' /etc/postgresql/*/main/postgresql.conf
   - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
   - sudo service postgresql restart
   - sleep 1
   - sudo service postgresql stop
   - sudo service postgresql start 11
   - postgres --version
before_script:
   - psql -c 'create database "test_db";' -U postgres
   - psql -Upostgres -hlocalhost -p5433 -c "SELECT version();"
script: true
