---
language: node_js
node_js:
  - "8"
before_install:
  - sudo mysql -e 'CREATE DATABASE asdfasd CHARACTER SET utf8 COLLATE utf8_general_ci;'
install: true
script: true
env:
  - CXX=g++-4.8
addons:
  mariadb: "10.3"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
