sudo: required
dist: bionic
addons:
  apt:
    packages:
    - postgresql-12
    - postgresql-12-postgis-3
before_install:
  - psql --version
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
before_script:
  - psql -c 'create database travis_ci_test2;' -U postgres
