os: linux
dist: xenial
language: ruby

env:
  global:
    - branchCon = master

if: ($branchCon = env(TRAVIS_BRANCH)) AND (type NOT IN (pull_request))

before_script:
  - echo $TRAVIS_BRANCH
  - echo $branchCon
