language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install -y postgresql-12 postgresql-client-12
before_script:
  - service postgresql restart
  - psql --version
  - ps -ef | grep postgres
  - sudo sed -i 's/port = 5207/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{10,11,12}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 12
  - sudo find /tmp/ -name .s.PGSQL.5432
  - psql -c 'create database travis_ci_test;' -U postgres
script: true
services:
  - postgresql
addons:
  postgresql: "12"
