language: ruby
dist: bionic
install: true
script:
  - cd /etc/elasticsearch/
  - ls -all
  - cat elasticsearch.yml
  - echo "xpack.security.enabled:false" > elasticsearch.yml
  #- sed -i 's/xpack.security.enable/xpack.security.enabled: false/g' elasticsearch.yml

services:
  - elasticsearch

before_install:
  - sudo chown -R $USER:elasticsearch /etc/default/elasticsearch
  - sudo chown -R $USER:elasticsearch /etc/elasticsearch
  - sudo service elasticsearch restart
  - curl -XGET 'http://localhost:9200'
  - "elasticsearch --version"
