---
os: linux
dist: jammy
language: python
python: "3.6"

install: true
script:
  - python -V
  - openssl version

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
