---
language: generic
os: osx
osx_image: xcode12.4
install:
  - brew cask install ugroupmedia/pnp/grpc-java
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

#services:
#  - docker

#jobs:
#  include:
#    - dist: bionic
#    - dist: xenial
#    - dist: trusty
#    - dist: focal
