---
language: python
os: linux
dist: xenial
jobs:
    include:
        arch: arm64
        os: linux
        env:
            - MB_PYTHON_VERSION=3.7
            - MB_ML_VER=2014
            - PLAT=aarch64
script: true
services:
    - docker
before_install:
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

deploy:
    provider: releases
    api_key:
        secure: "Ck9yLfvGypqfxD4njaCSbmnbzW88DFg5wv2/IbSx4mPu+Eu18qvpd17vg+JAP5zlE/nYE1JunJRiKN2Q40B/KDV1au9pz9MF/xF1YkrlKbwGuO0tFArJXrARKB0on2muR52jmskB3WNsDmvnC8sBM7jwXxjP7nSVvPsGy7fZU05rUT6xDyYdi4/KdwVyISq3g4is0rAKtM+u+UeiaHglCMqWznb0XkOPuxD5uhKnOu2UOn+tIEBwQuGBZ+1Y/Qs4DCv0TwSF98svjHEwcHliYxKfPsa1RV6o/lQHbv97o2DcQwX0eCFP68iPWIxexavewrUcu3aIEaYJS2nsiD40/Y3tO+pL7B4i6ETAeqXzC+KnQTpAd5qqdPPe7xchwpFyMRtJv24hk06hgrTrYtB7+tHoihesW27ZBhtUOsDubslEJzc7+aeQUy7pvw3rQtIYFJ7haaUox11w+LNXnZx+C4lBMNaexidOtlltcnlPLf21/91tEUsiNWjlH0QDj12wR0ZkA624d70flRyBDq9ih6Juc0h/DG7L/AYlmfvVrYED/v8JGeJgC7oJODLn4dTARdqLnUIkbcLrJp3t7W4nj3CZ4kewWOqDb2V+m4rcIya2fFLvldUyZG5t7MevXm/XZEmLnjbJYehq3LeJnwrY4ByKjOqrrvalVkol2UmHfuI="
    file: "./install.yml"
    skip_cleanup: true

# ====> Slack notification..
notifications:
    slack:
        secure: VoE5SUTQ3VkkJGyOOcpNJ4X1FyphB22Qa8Q27ZCYluhw1L02k2r/vWIsIGWe2KfStTlFupFeKqeF8QOYD8l9BxwOK6l7lDR9PUbR5paV8nD0wMs7OA8msTYXpvJH46fVdrmqVyRBFc+RE3ORw00TsHbShiNR+8zAhoEYFiwROZVsVvIBTfV4TZedYi6OW5Rg2NInf4mNX0fPKRVJTZ/euK+NIaKRticpAw0qfxK+seAyJ5UjqJ5QjMUa1lebq4vAETgk5g41ghQuhdLq1GIs7Na8+sCaQk+Yax4OxEsyy5yRmEkohxt0+cMHMKApbHl/5y2rQA6m5iJ8HliRJuWkSvTOxPeY2oQ4i8R7zY6l9y5IcYdU1M9MjfHzt0nQ6m4UUna0AWLdumGifhI+l8XtVhbHpQ2xd0oNVmOfF636JG+80WH3JJcbsOt8fwaxNeZP/HarpIB1XVrRtnVh3JaGsu3O1T6zoTZUBUwspQKK7k1Fl8sso+lCTNhoTPjgTiloOGhBFA4vBDF1U/JRdTksbXeLdx51Jx/8kyU6IXjsOU6bZLz3jZMRpQzy5TkNAO51mYnx4RoQF/QrBKSTp1OjZh+CaWUMBCzFTDqgONTbmesUD2PqbOkifaB1+0Rq9L46sNLM1YS4JZIpWNW6yg30tgjAqryI8Xu1W2Ka8153db4=
