services:
  - postgresql
  - redis
addons:
  chrome: stable
  postgresql: 11
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
before_install:
  - bundle --version
  - psql --version
