---
os: linux
dist: focal
language: ruby

before_install:
  - git clone git@github.com:owenthereal/upterm.git
  - cd upterm
  - go install ($pwd)/upterm/
script:
  - upterm host -- bash
  - upterm session current
