---
language: php
pho: 5.5
os:
    - linux
dist: focal
addons:
    firefox: "36.0"
cache:
    apt: true
    directories:
        - "$HOME/dwl"
        - "$HOME/.composer/cache"
        - ".cache/bower"
        - vendor
        - node_modules
jobs:
    include:
        - php: "5.5"
          env:
              - TESTGROUP: '"unit|acceptance_|origin_|functional_"'
        - php: "5.5"
          env:
              - TESTGROUP: '"selenium"'
services:
    - rabbitmq
    - redis
before_install:
    - composer selfupdate --1
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
      --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x16"
before_script:
    - phpenv config-rm xdebug.ini
    - export DISPLAY=:99.0
    - "./bin/travis/init-travis.sh"
    - umask 0000
    - sudo mkdir -p app/logs app/cache
    - sudo chmod -R 777 app/logs app/cache
    - phpenv config-add travis.php.ini
    - "./bin/travis/services-travis.sh"
    - php vendor/doctrine/phpcr-odm/bin/phpcrodm phpcr:workspace:create editiontest ||
      true
    - php app/console cache:warmup --env=test
    - "./node_modules/bower/bin/bower install -q"
    - sudo sed s/16M/128M/ /etc/mysql/my.cnf >> /dev/null
    - sudo service mysql restart
    - php app/console assets:install --env=test
    - php app/console assetic:dump --env=test
    - php app/console doctrine:schema:update --force --env=test --em=origin
    - php app/console doctrine:schema:update --force --env=test --em=origin_pnw
script: true

# ====> Slack notification..
notifications:
    slack:
        secure: VoE5SUTQ3VkkJGyOOcpNJ4X1FyphB22Qa8Q27ZCYluhw1L02k2r/vWIsIGWe2KfStTlFupFeKqeF8QOYD8l9BxwOK6l7lDR9PUbR5paV8nD0wMs7OA8msTYXpvJH46fVdrmqVyRBFc+RE3ORw00TsHbShiNR+8zAhoEYFiwROZVsVvIBTfV4TZedYi6OW5Rg2NInf4mNX0fPKRVJTZ/euK+NIaKRticpAw0qfxK+seAyJ5UjqJ5QjMUa1lebq4vAETgk5g41ghQuhdLq1GIs7Na8+sCaQk+Yax4OxEsyy5yRmEkohxt0+cMHMKApbHl/5y2rQA6m5iJ8HliRJuWkSvTOxPeY2oQ4i8R7zY6l9y5IcYdU1M9MjfHzt0nQ6m4UUna0AWLdumGifhI+l8XtVhbHpQ2xd0oNVmOfF636JG+80WH3JJcbsOt8fwaxNeZP/HarpIB1XVrRtnVh3JaGsu3O1T6zoTZUBUwspQKK7k1Fl8sso+lCTNhoTPjgTiloOGhBFA4vBDF1U/JRdTksbXeLdx51Jx/8kyU6IXjsOU6bZLz3jZMRpQzy5TkNAO51mYnx4RoQF/QrBKSTp1OjZh+CaWUMBCzFTDqgONTbmesUD2PqbOkifaB1+0Rq9L46sNLM1YS4JZIpWNW6yg30tgjAqryI8Xu1W2Ka8153db4=
