---
jobs:
  - name: Run Wholesale Tests
    language: python
    python:
      - "3.8"
    services:
      - mysql
      - redis
      - docker
    env:
      - MYSQL_HOST=127.0.0.1 MYSQL_REPLICA_HOST=127.0.0.1 REDIS_HOSTNAME=127.0.0.1 LOG_LEVEL=50
    before_install:
      - sudo apt-get update && sudo apt-get install -y git-crypt gnupg
      - echo -e "$GPG_PRIVATE_KEY" | gpg --import
      - git-crypt unlock
      - sudo mysql -e "CREATE DATABASE IF NOT EXISTS master;"
      - sudo mysql -e "CREATE USER IF NOT EXISTS 'canold'@'%' IDENTIFIED BY 'canold'";
      - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'canold'@'%'";
      - sudo mysql -e "FLUSH PRIVILEGES";
      - sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'canold';"
    install:
      - python3 -m pip install -r scripts/tasks/requirements.txt
    before_script:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - export PATH=$PATH:$(pwd)/scripts
    script: ./scripts/test api-wholesale
  - name: Run Treez Tests
    language: python
    python:
      - "3.8"
    services:
      - mysql
      - redis
      - docker
    env:
      - MYSQL_HOST=127.0.0.1 MYSQL_REPLICA_HOST=127.0.0.1 REDIS_HOSTNAME=127.0.0.1 LOG_LEVEL=50
    before_install:
      - sudo apt-get update && sudo apt-get install -y git-crypt gnupg
      - echo -e "$GPG_PRIVATE_KEY" | gpg --import
      - git-crypt unlock
      - sudo mysql -e "CREATE DATABASE IF NOT EXISTS master;"
      - sudo mysql -e "CREATE USER IF NOT EXISTS 'canold'@'%' IDENTIFIED BY 'canold'";
      - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'canold'@'%'";
      - sudo mysql -e "CREATE DATABASE IF NOT EXISTS treez;"
      - sudo mysql -e "CREATE USER IF NOT EXISTS 'treez'@'%' IDENTIFIED BY 'canold'";
      - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'treez'@'%'";
      - sudo mysql -e "FLUSH PRIVILEGES";
      - sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'canold';"
    install:
      - python3 -m pip install -r scripts/tasks/requirements.txt
    before_script:
      - export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/treez/src
      - export PATH=$PATH:$(pwd)/scripts
    script: ./scripts/test api-treez
  - name: Run qr-taskbot Tests
    language: python
    python:
      - "3.8"
    services:
      - mysql
      - redis
      - docker
    env:
      - MYSQL_HOST=127.0.0.1 MYSQL_REPLICA_HOST=127.0.0.1 REDIS_HOSTNAME=127.0.0.1 LOG_LEVEL=50
    before_install:
      - sudo apt-get update && sudo apt-get install -y git-crypt gnupg
      - echo -e "$GPG_PRIVATE_KEY" | gpg --import
      - git-crypt unlock
      - sudo mysql -e "CREATE DATABASE IF NOT EXISTS master;"
      - sudo mysql -e "CREATE USER IF NOT EXISTS 'canold'@'%' IDENTIFIED BY 'canold'";
      - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'canold'@'%'";
      - sudo mysql -e "FLUSH PRIVILEGES";
      - sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'canold';"
    install:
      - python3 -m pip install -r scripts/tasks/requirements.txt
    before_script:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - export PATH=$PATH:$(pwd)/scripts
    script: ./scripts/test qr-taskbot
  - name: Run qr-metrcpackage Tests
    language: python
    python:
      - "3.8"
    services:
      - mysql
      - redis
      - docker
    env:
      - MYSQL_HOST=127.0.0.1 MYSQL_REPLICA_HOST=127.0.0.1 REDIS_HOSTNAME=127.0.0.1 LOG_LEVEL=50
    before_install:
      - sudo apt-get update && sudo apt-get install -y git-crypt gnupg
      - echo -e "$GPG_PRIVATE_KEY" | gpg --import
      - git-crypt unlock
      - sudo mysql -e "CREATE DATABASE IF NOT EXISTS master;"
      - sudo mysql -e "CREATE USER IF NOT EXISTS 'canold'@'%' IDENTIFIED BY 'canold'";
      - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'canold'@'%'";
      - sudo mysql -e "FLUSH PRIVILEGES";
      - sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'canold';"
    install:
      - python3 -m pip install -r scripts/tasks/requirements.txt
    before_script:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - export PATH=$PATH:$(pwd)/scripts
    script: ./scripts/test qr-metrcpackage
  - name: Check Migrations
    language: python
    python:
      - "3.8"
    services: {}
    before_install:
    install:
      - python3 -m pip install PyGithub==1.55
      - python3 -m pip install ./weed
    script: python3 deploy/automation/check-migrations.py
