os: linux
rvm: 2.6.6
language: ruby
dist: bionic
group: dev
services:
- postgresql
- redis
addons:
  chrome: stable
  postgresql: '11.7'
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
before_install:
- psql --version
install: skip
