language: shell


jobs:
  include: 
    - if: env(TEST_VAR) = "test"
      script: echo MERHABA
    - if: if [[ $TEST_VAR = "test" ]]; then echo asdfasdfasdfasdfasdfasdfasdf; fi
      script: echo oyle
