---
# https://blog.travis-ci.com/2018-10-11-windows-early-release
# https://docs.travis-ci.com/user/reference/windows
# https://chocolatey.org/packages/python
os: windows # Windows Server, version 1803
language: sh # 'language: python' is not yet supported

py27-steps: &py27-steps
  env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
  before_install:
    - choco install python2
    - python -m pip install --upgrade pip

py35-steps: &py35-steps
  env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
  before_install:
    - choco install python --version 3.5.4
    - python -m pip install --upgrade pip

py36-steps: &py36-steps
  env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
  before_install:
    - choco install python --version 3.6.8
    - python -m pip install --upgrade pip

py37-steps: &py37-steps
  env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  before_install:
    - choco install python --version 3.7
    - python -m pip install --upgrade pip

py38-steps: &py38-steps
  env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  before_install:
    - choco install python --version 3.8
    - python -m pip install --upgrade pip

py39-steps: &py39-steps
  env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
  before_install:
    - choco install python --version 3.9
    - python -m pip install --upgrade pip

py310-steps: &py310-steps
  env: PATH=/c/Python310:/c/Python310/Scripts:$PATH
  before_install:
    - choco install python --version 3.10
    - python -m pip install --upgrade pip

matrix:
  include:
    - name: "Python 2.7: Run tests"
      <<: *py27-steps
    - name: "Python 3.5: Run tests"
      <<: *py35-steps
    - name: "Python 3.6: Run tests"
      <<: *py36-steps
    - name: "Python 3.7: Run tests"
      <<: *py37-steps
    - name: "Python 3.8: Run tests"
      <<: *py38-steps
    - name: "Python 3.9: Run tests"
      <<: *py39-steps
    - name: "Python 3.10: Run tests"
      <<: *py310-steps
install: true
script:
  - python --version
  - python -m pip install --upgrade pip
  - pip install -e .[dev]
