language: shell
script: echo hello
- stage: stage_deploy
    script: skip
    if: |
      type = push AND \
      branch =~ ^\d+\.\d+$
    deploy:
    provider: script
    script: ./bin/deploy.sh
    on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^\d+\.\d+$
