#addons:
#    sauce_connect:
#      username: testSauce44
language: shell
script: 
  - |
    if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)" ]]; then
      echo "Commit $(git rev-parse HEAD) doesn't match expected commit $TRAVIS_COMMIT. When this occurs, there should be a more recent build for a newer commit, so this build can be ignored."
      exit 1
    fi
