language: shell
env:
    global:
        - qwer=0
    jobs:
        - asdf=spec/US/modal
script:
  - echo $qwer
  - echo $asdf

jobs:
  include:
    - name: 'test'
      if: $qwer=0
    - name: 'test2'
      if: $asdf=spec/US/modal
    - name: 'test3'
      if: $qwer=2
deploy:
  provider: script
  script: deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(test|master)$
