node_js:
  - 12
  - 10

jobs:
  include:
    - dist: xenial
      language: shell
      name: Bash test1
      script:
        - ./bash/test/softHSMTest.sh
    - os: osx
      language: node_js
      node_js:
        - "12"
      script:
        - cd nodejs; npm test
    - os: osx
      language: shell
      name: Bash test2
      script:
        - ./bash/test/softHSMTest.sh
    - dist: xenial
      language: node_js
      node_js:
        - "12"
      script:
        - cd nodejs
