---
#language: generic
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

#services:
#  - docker

#jobs:
#  include:
#    - dist: bionic
#    - dist: xenial
#    - dist: trusty
#    - dist: focal
#    ---

language: android
dist:
  - trusty
  - focal
  - xenial
  - bionic
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-29.0.3
  - extra
before_install:
  - yes | sdkmanager "platforms;android-30"
