<<<<<<< HEAD
dist: bionic

env:
  global:
    - PGPORT=5433
    - PGUSER=travis

addons:
  apt:
    packages:
      - postgresql-12
  postgresql: '12'

before_install:
   - echo 'installing postgresql'
   - sudo sed -i 's/port = 5432 */port = 5433/' /etc/postgresql/12/main/postgresql.conf
   - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
   - sudo service postgresql restart
   - sleep 1
   - sudo service postgresql stop
   - sudo service postgresql start 12
   - postgres --version
before_script:
   - psql -c 'create database "test_db";' -U postgres
   - psql -Upostgres -hlocalhost -p5433 -c "SELECT version();"
script: true
=======
language: ruby
dist: bionic
addons:
    postgresql: '12'
    apt:
      packages:
        - postgresql-12
env:
    global:
  - PGUSER=postgres
  - PGPORT=5432
  - PGHOST=localhost

before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1

script: 
  - psql -c 'create database travis_ci_test;' -U postgres
>>>>>>> 5e1bf60824fbd6492ea5af72bfedaeb96d5a556d
