dist: xenial
sudo: required

language: php

php:
  - '5.6'

services:
  - docker
  - xvfb

addons:
  chrome: stable

before_install:
  - google-chrome-stable --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &
script: true
