os: osx
language: ruby
rvm: 2.3.0
script: echo ruby2.3.0
jobs:
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy
