---
os: linux
language: generic
install: true
addons:
  apt:
    update: true
    packages:
      - openssh-client

script:
  - ssh -V

jobs:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic
