os:
  - linux
  - osx

language: ruby

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install graphviz; else brew install graphviz; fi

rvm:
  - 2.6

script:
  - bundle exec rspec
