language: bash

addons:
  apt:
    packages:
    - libgconf-2-4
    
install:
  - npm install

stages:
  - test
  - name: tag
    if: branch = test
    script: echo TAG STAGE SCRIPT
  - name: publish
    if: branch = test
    script: echo PUBLISH STAGE SCRIPT

jobs:
  include:
    - stage: test
    - stage: tag
    - stage: publish
