---
os: linux
language: generic

install: true

script:
  - ifconfig

jobs:
  include:
    - arch: arm64
      name: ets
    - arch: arm64
      name: adfasd
    - arch: arm64
      name: sadasdaa
    - arch: arm64
      name: asdfasdf
    - arch: arm64
