addons: 
  apt: 
    packages: 
      - postgresql-10
      - postgresql-client-10
  postgresql: 12

before_install:
  - sudo apt-get update
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 10
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install: true
script: true
services:
  - postgresql
