script: true
addons:
    sauce_connect:
      username: testSauce44
      access_key:
        secure: kcJGjv5522jL3naHMQ/MPaGBe9Rdi6X9yMlLW7c2376lsiMAEug9rIwCIIzmXP71d8XAPxYY1MIxrxFMbQD7S/Z8zSDf7nOVSUVTIGpEpOnaGBHxAw8OZeXr1kabLLSqWcIzBRA1V1vUauxnxoACtv50A2SBOZRojzAlil/X9sOOyskpHV9M40NxY/t5Dpf2oPKxyjJgnB3ZhDKKbmJH4GOCA09wi7J0QlLAgVb6WLctl7E7CEUETSRzj28Q5nbiFTampqy4sMwnKEKxtam2b6INO5A4cpRVmCxRkot36Rb/X/gH6PK74kXQbVgQhPPY2p5QZ4wzHT2VLMNgd+C2tdlLFdrMDif+79CCxuFl71zriL8J4lhnN0LWH2G7zQlpxh3EAouxRmMCzTwFX1n9ayA5ZxHy4gPkeVMovEuv1klOPGbykEWFbZFPdJ1+z7zED7xvZCIkAtaY/4olE52vLw6862o0Q5YGL6dMiEwEccWEoa0HVZDanz2BYY9J7XOmlIi5HGhovkrWRS/oyxRR6Gt4iCqEDKoov8Y05P26jj1GVYLiTlLgzXOPdahE4lMZMbDAer8s6eD7HostYqqzK2moYcI9cQ706s7nY4AXnHTYD1OnKjBRP5HUv2JHlikO3JBjYoH6XDLeV2bR4E0+SI1Ph51Yk6muxUYmO+s7xrc=
