language: ruby
before_install: # for bundler 2.0+
  - gem install bundler
script: true
matrix:
  include:
    # Linux - Tests and Linting
    - os: linux
      rvm: 2.6
    - os: linux
      rvm: 2.5
    - os: linux
      rvm: 2.4
    # OS X - Tests
    - os: osx
      rvm: 2.6
    - os: osx
      rvm: 2.5
    - os: osx
      rvm: 2.4
