jobs:
  include:
    - stage: "Build OS"
      name: "Building Xenial distro"
      language: shell
      os: linux
      dist: xenial
      workspaces:
        create:
          name: linux-os

    - stage: "Update & install tools"
      name: "JDK install, apt update & git clone"
      workspaces:
        create:
          name: build-tools


    - stage: "Assembling environment"
      name: "Exports to PATH, cache dir's & assemble project"
      workspaces:
        create:
          name: image


    - stage: "Tests"
      name: "API Tests"
      workspaces:
        use:
          - image

    - name: "GUI Tests"
      workspaces:
        use:
          - image

    - stage: "Post archive"
      name: "Cleanups & send report e-mail"
      workspaces:
        use:
          - image
