---
os: linux
dist: focal

language: node_js
node_js: 14

install: curl -X GET "http://localhost:9200"

script: nproc
before_install:
  - curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb https://artifacts.elastic.co/packages/7.9.0/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.9.0.list
  - sudo apt update
  - sudo apt-get install elasticsearch
  - systemctl enable elasticsearch.service
  - systemctl start elasticsearch.service
