language: node_js
script:
  - |
    if [ "$TRAVIS_PULL_REQUEST_SLUG" = "mustafa-travisci/testBuilds" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "master" ]; then
     export PERCY_BRANCH ="fork-${TRAVIS_BUILD_NUMBER};
    fi
