language: php
php:
  - 7.0
before_script:
  - sudo apt-get -y install gcc make autoconf libc-dev pkg-config
  - sudo apt-get -y install libssh2-1-dev
  - sudo pecl7.X-sp install ssh2-alpha
script: 
  - sudo bash -c "echo extension=ssh2.so > /etc/php7.X-sp/conf.d/ssh2.ini"
  - sudo service php7.X-fpm-sp restart
after_script:
  - phpX.Y-sp -i | grep ssh2
