---
os: linux
dist: xenial
language: python

install: pip install .

jobs:
  include:
    - python: 3.7
      script:
        - ls -lt /home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/
        - ls -lt /home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/setuptools*
    - python: 3.8
      script:
        - ls -lt /home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/
        - ls -lt /home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/setuptools*
