---
dist: xenial
language: java

script:
  - java --version

before_install:
  - sudo apt-get -y remove default-jdk
  - sudo apt -y autoremove
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 17.0.2-open
  - java -version

install: true
