language: shell
script: true
notifications:
  email:
    recipients:
      -mustafa@travis-ci.org
    on_success: always
    on_failure: always 

deploy:
  provider: script
  script: bash deploy.sh
  on:
    condition: "true"
