---
os: linux
language: php
php: nightly
script: 
  - php -version

install: true
branches:
  only:
    - master

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
      group: edge
