language: shell

script: if [[ $TEST_VAR = "test" ]]; then echo asdfasdfasdfasdfasdfasdfasdf; fi

jobs:
  include: 
    - if: env(TEST_VAR) = "tesst"
      script: echo MERHABA
    - name: oyle
      script: echo oyle
