language: minimal

before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

jobs:
  include:
    - stage: test
      dist: xenial
      script: docker pull alpine

    - stage: test_2
      script: docker pull alpine
