language: shell

jobs:
  include:
    - script: echo "test_1" # uses the default stage name "test"
    - script: echo "test_2"
    - stage: deploy
      script: skip     # usually you do not want to rerun any tests
      deploy: &script
        provider: script
        script: echo "Deployment sucessfull!!!"
