language: php

env:
    matrix:
        - CI_NODE_TOTAL=10 INDEX=2
        - CI_NODE_TOTAL=10 INDEX=3
        - CI_NODE_TOTAL=10 INDEX=4
      
stages:
  - test
  - functional tests
  - name: deploy
    if: branch = test
      
jobs:
    - stage: test
      env: CI_NODE_TOTAL=10 INDEX=1
      script: echo testStage
    - stage: func test
      script: echo funcTestStage
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: test.sh
