language: cpp
jobs:
  include:
    - name: "Linux / clang / x86_64"
      os: linux
      compiler: clang
    - name: "Linux / gcc / x86_64, i686"
      os: linux
      compiler: gcc
    - name: "Linux / gcc / aarch64"
      compiler: gcc
      arch: arm64
    - name: "Linux / gcc / ppc64le"
      arch: ppc64le
      os: linux
      compiler: gcc
    - name: "macOS / clang / x86_64"
      os: osx
      compiler: clang
    - name: "aaWindows / MSVC / x64, Win32"
      os: windows
