language: generic
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
services:
  - docker
dist: xenial
if: type=pull_request AND branch=~ /(^test2$)/
