language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.37.0

allow_failures:
  - rust: nightly
  - os: windows

jobs:
  include:
    - if: rust = stable OR rust = beta OR rust = nightly
      script:
        - cargo build
        - cargo doc --all-features --no-deps
        - cargo test --release
        - cargo test --release --no-default-features
        - cargo test --release --all-features

    - if: rust = "1.37.0"
      script:
        - cargo build --release
        - cargo build --release --no-default-features
        - cargo build --release --all-features
