language: shell
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
jobs:
  include:
    - name: Bionic
      dist: bionic
    - name: Focal
      dist: Focal
