dist: trusty
language: bash
jobs:
  include:
    # Fake job for debugging.
    - if: env(TEST_VAR) IS present
      name: This works
      scripts:
        - env
    - if: env(TEST_VAR) IS present
      name: This does not work
      env:
        - ANYTHING=HERE
      scripts:
        - env
