language: ruby
rvm:
  - 2.6.6
dist: bionic
addons:
  postgresql: 11
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
before_install:
  - psql --version
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
