language: shell
sudo: required
dist: focal
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - xdpyinfo -display :0 >/dev/null 2>&1 && echo "In use" || echo "Free"
