language: ruby
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
cache:
  - bundler
  - directories:
    - /home/travis/.rvm/
rvm:
  - 2.3.8
script: ruby test.rb
