sudo: required
language: bash

services:
  - docker
  - mysql
  
addons:
  apt:
   packages:
    - mysql-server
    - mysql-client

before_install:
- sudo cp $TRAVIS_BUILD_DIR/_travis/mysql.cnf /etc/mysql/conf.d/
- sudo service mysql restart
