---
language: python
os:
    - linux
dist: xenial
env:
    global:
        - REPO_DIR: python-driver
        - BUILD_COMMIT: asdasdasd
        - BUILD_DEPENDS: '"geomet>=0.1,<0.3 six>=1.9 futures<=2.2.0 Cython>=0.20,!=0.25,<0.30"'
        - TEST_DEPENDS: '""'
        - UNICODE_WIDTH: "32"
python:
    - "3.5"
services:
    - docker
jobs:
    include:
        - env:
              - MB_PYTHON_VERSION: "2.7"
        - env:
              - MB_PYTHON_VERSION: "2.7"
              - UNICODE_WIDTH: "16"
        - env:
              - MB_PYTHON_VERSION: "2.7"
              - PLAT: i686
        - env:
              - MB_PYTHON_VERSION: "2.7"
              - PLAT: i686
              - UNICODE_WIDTH: "16"
        - env:
              - MB_PYTHON_VERSION: "3.5"
        - env:
              - MB_PYTHON_VERSION: "3.5"
              - PLAT: i686
        - env:
              - MB_PYTHON_VERSION: "3.6"
        - env:
              - MB_PYTHON_VERSION: "3.6"
              - PLAT: i686
        - env:
              - MB_PYTHON_VERSION: "3.7"
        - env:
              - MB_PYTHON_VERSION: "3.7"
              - PLAT: i686
        - arch: arm64
          os: linux
          services:
              - docker
          env:
              - MB_PYTHON_VERSION: "3.7"
              - MB_ML_VER: "2014"
              - PLAT: aarch64
        - env:
              - MB_PYTHON_VERSION: "3.8"
        - env:
              - MB_PYTHON_VERSION: "3.8"
              - PLAT: i686
        - arch: arm64
          os: linux
          services:
              - docker
          env:
              - MB_PYTHON_VERSION: "3.8"
              - MB_ML_VER: "2014"
              - PLAT: aarch64
        - os: osx
          osx_image: xcode11
          language: generic
          env:
              - MB_PYTHON_VERSION: "2.7"
        - os: osx
          osx_image: xcode11
          language: generic
          env:
              - MB_PYTHON_VERSION: "3.5"
        - os: osx
          osx_image: xcode11
          language: generic
          env:
              - MB_PYTHON_VERSION: "3.6"
        - os: osx
          osx_image: xcode11
          language: generic
          env:
              - MB_PYTHON_VERSION: "3.7"
        - os: osx
          osx_image: xcode11
          language: generic
          env:
              - MB_PYTHON_VERSION: "3.8"

script: true


# ====> Slack notification..
notifications:
    slack:
        secure: VoE5SUTQ3VkkJGyOOcpNJ4X1FyphB22Qa8Q27ZCYluhw1L02k2r/vWIsIGWe2KfStTlFupFeKqeF8QOYD8l9BxwOK6l7lDR9PUbR5paV8nD0wMs7OA8msTYXpvJH46fVdrmqVyRBFc+RE3ORw00TsHbShiNR+8zAhoEYFiwROZVsVvIBTfV4TZedYi6OW5Rg2NInf4mNX0fPKRVJTZ/euK+NIaKRticpAw0qfxK+seAyJ5UjqJ5QjMUa1lebq4vAETgk5g41ghQuhdLq1GIs7Na8+sCaQk+Yax4OxEsyy5yRmEkohxt0+cMHMKApbHl/5y2rQA6m5iJ8HliRJuWkSvTOxPeY2oQ4i8R7zY6l9y5IcYdU1M9MjfHzt0nQ6m4UUna0AWLdumGifhI+l8XtVhbHpQ2xd0oNVmOfF636JG+80WH3JJcbsOt8fwaxNeZP/HarpIB1XVrRtnVh3JaGsu3O1T6zoTZUBUwspQKK7k1Fl8sso+lCTNhoTPjgTiloOGhBFA4vBDF1U/JRdTksbXeLdx51Jx/8kyU6IXjsOU6bZLz3jZMRpQzy5TkNAO51mYnx4RoQF/QrBKSTp1OjZh+CaWUMBCzFTDqgONTbmesUD2PqbOkifaB1+0Rq9L46sNLM1YS4JZIpWNW6yg30tgjAqryI8Xu1W2Ka8153db4=
