---
jobs:
  include:
    - # Rails Api tests
      stage: test
      language: ruby
      rvm:
        - 2.7.5
      services:
        - postgresql
      addons:
        postgresql: 9.6
        apt:
          update: true
          packages:
            - postgresql-client
      script: true
      cache: bundler

    - # React App tests
      language: node_js
      node_js: 12.22.7
      env: JEST_SILENT_REPORTER_DOTS=true
      script: true
      cache: yarn

    - # Heroku and sentry deploy
      stage: deploy
      language: node_js
      node_js: 12.22.7
      install:
        - curl -sL https://sentry.io/get-cli/ | bash
      script: skip
      before_deploy:
        - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3 # https://travis-ci.community/t/heroku-deploy-fails-installing-dpl-heroku-encounters-faraday-error/12563/5
      deploy:
        - provider: heroku
          api_key:
            secure: 5nt/mshzVC8l3HnqtcXq/bfmJChVALZGQUAzf8PjSa6+9DuFmLHe+PAdnzE6ZIv0srU5st6VYDi8xlmQ1NykYadu9uB9SvZyxiHg+gDXxaVhYRqpKBOdgo4Ic2RsTTRqafpbcxL1/ALUFyiw891mxmNorUTqjK79k5k4/+sx9iE4fE0GRq15PCHn84hEg7H+isRhhgCZ7qnuwELWKGXFlI7f7DYYt5xfS4kmxQLkCZDs8cmPQ8Im3YHDLFUDIJRC2G7OpioHF2uXEUlA7QlI7OCY54+PLZQF4lrXt4IhIFnDfjbsxOQPrhhrx+kLiPcRfRB1/7fOez6tF/DSvgygANbMCi4NK/fDE9ZGRfB+LfAK02sP/PtthlnXGO5NxFjywnbLdBKOyqerNrq1X8BzLqRZjbDvqYekx4iG03e46ng9NcIg1EF6K3M+3NQxcLhBQ3yOt473icYXxZ/sTcMnwtiAdZ1vnaXe9lCbnMZ3Jr/KE/02kqhx3WZJ6lIaKzAXsVmTPuax3tDiY7EzL6PzW50/n+BcQ+zGEfEyyuOsvVG07APlctFbWjRjzSmwLfWKG37pcQrMo2M6Byixvo9HF7ReUXr2drF6GO0P5OsvFGNbjQGslsgPIm/ZrGkV4slgbtY44jZaSN6pXU=
          run:
            - rake db:migrate

# ====> Slack notification...
notifications:
  slack:
    secure: VoE5SUTQ3VkkJGyOOcpNJ4X1FyphB22Qa8Q27ZCYluhw1L02k2r/vWIsIGWe2KfStTlFupFeKqeF8QOYD8l9BxwOK6l7lDR9PUbR5paV8nD0wMs7OA8msTYXpvJH46fVdrmqVyRBFc+RE3ORw00TsHbShiNR+8zAhoEYFiwROZVsVvIBTfV4TZedYi6OW5Rg2NInf4mNX0fPKRVJTZ/euK+NIaKRticpAw0qfxK+seAyJ5UjqJ5QjMUa1lebq4vAETgk5g41ghQuhdLq1GIs7Na8+sCaQk+Yax4OxEsyy5yRmEkohxt0+cMHMKApbHl/5y2rQA6m5iJ8HliRJuWkSvTOxPeY2oQ4i8R7zY6l9y5IcYdU1M9MjfHzt0nQ6m4UUna0AWLdumGifhI+l8XtVhbHpQ2xd0oNVmOfF636JG+80WH3JJcbsOt8fwaxNeZP/HarpIB1XVrRtnVh3JaGsu3O1T6zoTZUBUwspQKK7k1Fl8sso+lCTNhoTPjgTiloOGhBFA4vBDF1U/JRdTksbXeLdx51Jx/8kyU6IXjsOU6bZLz3jZMRpQzy5TkNAO51mYnx4RoQF/QrBKSTp1OjZh+CaWUMBCzFTDqgONTbmesUD2PqbOkifaB1+0Rq9L46sNLM1YS4JZIpWNW6yg30tgjAqryI8Xu1W2Ka8153db4=
