os: linux
dist: bionic
language: ruby

services:
  - postgresql

rvm:
  - 2.7.1

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

env:
  global:
    - PGPORT=5433
    - PGVER=12

before_script:
  - psql -c 'create database "test_db";'
