language: shell
before_script:
- heroku auth:login
script: true
env:
  global:
    secure: iR3MqQmUdrOIUlG+4sP0xZ2DKaiEQGdQ6vlxBNXt+OeB2tutFzOIM9MaQvCoeQypGmSUwDWAfjXXOhag54Hy51BQWZXQ8Cwn+aevtumfInYtMfRmWLDAJRUBP/GCCav7wnbrS8xpFPu7oOnFLr49X4toP3CR8fuzbYRMV8GckkP6FlUu9Fe9RvUcQbgDl/7F8VrUhlh1X9lNSiRhvjzIEzas4dBbFvRlVPfLaAuUaXsuHsazBtwNWnT9xszzq2mLGArDTac+7t4UREpuvTbw0IgppqmCzgBg+NflrMCRrrV47dfjZEdFI+Uo5NG0N3pQr0FCJWq0GGQP+hLZrlaLjBP1LKsxFg4S3mB7NEU2PhxZaD0HFU2z0xjJc97dyqtB1HdXpSKVcnBNLoDbrmZaoIsABuvvLu0kOP4H6DA7HZ7QZW+cbxW1ZQkGiPkFHls3L7GTJXGhxTUVaSuuIiVdcCL2oh9nI/Uuhile+m3sN+le1NIcbLZquKdLbOkSW6ykLOYaoVbg9gOdpJquKPHa9r/NEo+kOiri4W5FV+pmYdMir1X+3nlnEC3pA0lEGGLOCd8BfgkryUCUXnfaBR4aOHM406/hC8xK1ba3L9wBludgoHbe/LedZ563RXZ/Kx/lNCFfEe7l0U5jYKRdDbDpVmSRK5JdLJWsrwt5IAPIHrQ=
