dist: xenial

sudo: true


services:
  - docker

before_install:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - ls /home/$USER/.docker
script:
  - sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
  - sudo chmod g+rwx "/home/$USER/.docker" -R
  - docker run -it guru:$(cat TAG) nosetests -services
