---
os: linux
language: go
env:
  global:
    - GIMME_DEBUG=1
go:
  - master
script:
  - go version
install: skip

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
