---
dist: xenial
jobs:
  allow_failures:
    - rvm: 2.5.3
  include:
    - stage: warm_cache
      rvm: 2.5.3
      script:
        - echo $TRAVIS_TEST_RESULT
        - export status=$( cat test.sh )
        - echo $status
      after_script:
        - echo $TRAVIS_TEST_RESULT
        - echo $TRAVIS_TEST_RESULT | tee test.sh
      workspaces:
        create:
          name: ws1
          paths:
            - ./test.sh
    - stage: warm_cache2_fail
      rvm: 2.5.3
      script:
        - cmake 22222
        - printf $TRAVIS_TEST_RESULT >> test.sh
        - export status=$( cat test.sh )
        - echo $status
      workspaces:
        create:
          name: ws1
          paths:
            - ./test.sh
    - stage: use_cache
      workspaces:
        use: ws1
      script:
        - export status=$( cat test.sh )
        - echo $status
