matrix:
  include:
    - language: php
      php: 7.4
      services:
        - redis-server
      install:
        - composer install --prefer-dist --no-suggest --optimize-autoloader --apcu-autoloader --no-ansi --no-interaction
      before_script:
        - echo '' | pecl install redis
      script:
        - composer test

    - language: python
      python: 3.6
      script: true
