---
language: python

python:
  - 3.9.7
  - 3.8

install:
  - pip3 install .

before_script:
  - pip3 install pytest

script:
  - pytest

stages:
  - name: test
    if: tag IS blank

jobs:
  include:
    - name: test
      script:
        - source ~/virtualenv/python3.9/bin/activate
    - script: echo "eeeee"
