language: shell
env:
    global:
        - qwer=0
    jobs:
        - asdf=spec/US/modal
script:
  - echo $qwer
  - echo $asdf
deploy:
  provider: script
  script: deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(test|master)$
