---
dist: xenial
language: generic
addons:
  sonarcloud:
    organization: mustafa-travisci
    token: $SONAR_TOKEN
before_install: true
install: true
script:
  - sonar-scanner --version
  - sonar-scanner
