language: shell
os: linux
dist: trusty
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6
    - postgresql-9.6-postgis-2.3
    - openjdk-8-jdk
jdk: openjdk8
before_install:
  - psql --version
  - java --version
