<<<<<<< HEAD
---
os: linux
dist: bionic
language: perl
perl:
  - "5.34"

install: true
script:
  - perl -v

###############################################################################
notifications:
  slack:
    secure: VoE5SUTQ3VkkJGyOOcpNJ4X1FyphB22Qa8Q27ZCYluhw1L02k2r/vWIsIGWe2KfStTlFupFeKqeF8QOYD8l9BxwOK6l7lDR9PUbR5paV8nD0wMs7OA8msTYXpvJH46fVdrmqVyRBFc+RE3ORw00TsHbShiNR+8zAhoEYFiwROZVsVvIBTfV4TZedYi6OW5Rg2NInf4mNX0fPKRVJTZ/euK+NIaKRticpAw0qfxK+seAyJ5UjqJ5QjMUa1lebq4vAETgk5g41ghQuhdLq1GIs7Na8+sCaQk+Yax4OxEsyy5yRmEkohxt0+cMHMKApbHl/5y2rQA6m5iJ8HliRJuWkSvTOxPeY2oQ4i8R7zY6l9y5IcYdU1M9MjfHzt0nQ6m4UUna0AWLdumGifhI+l8XtVhbHpQ2xd0oNVmOfF636JG+80WH3JJcbsOt8fwaxNeZP/HarpIB1XVrRtnVh3JaGsu3O1T6zoTZUBUwspQKK7k1Fl8sso+lCTNhoTPjgTiloOGhBFA4vBDF1U/JRdTksbXeLdx51Jx/8kyU6IXjsOU6bZLz3jZMRpQzy5TkNAO51mYnx4RoQF/QrBKSTp1OjZh+CaWUMBCzFTDqgONTbmesUD2PqbOkifaB1+0Rq9L46sNLM1YS4JZIpWNW6yg30tgjAqryI8Xu1W2Ka8153db4=
=======
langugage: shell
if: type IN (push, api)
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      secure: c5acO75w0j/IUKbTCd1sWmTY3D27GDLtGZ4fwg14U8esartvv2OKUq7CBLolduAIQdKZunR5vQEbE/pKCxTHGCwYI1yLEYn9pgtf7FYfLirmgc/C0vzx7g/qCzfxBhHtb4bFy1Nr7MdRSOzcs24VYWgjV+rsGMg46swJi7cVNJTe06PuAoI0Udm5lK9zdEF0WAcGmSReHQVWzNFs/ncHuR2VYZSf/AYECP7aLPIKwhWTbR+0OLXfAVT+gC2T6/6hp0EfGV2Ikxhy6c00CsghDTa7jitSxNR9Wp6NXB/JvXeQQN1Jsdv6geJPfn1vIkGyfXRBNKZbPPT8F2GK3tDpUTx+im27i0WfdFW8XDV7Gkxw1U+KPg2ukWL90ccT0/RBJGLnPY693dDihzoKb/XXbimt6rr1/dRdCTBwLrmLUepUESx2/A6s679xZXaHACWlPrB4rvUy5oFTtdl9IQ7HdYhqkRyfMR+3u0fgmeGWRsc7kKVd5lY135DL2MZEWcCW5GFdcOMg4ZSOxMXQ63BvKEp8nbbaagOScMIkIn1yda1zvzrDOaO52jLqbDfnnvaC+9BP9rXkASCcmjo4LiNiGhDSf0zP/xv48UEpZBp8isEJir5930O9FyehDNdBrZMvlq9B7C6cCuQoEq1f9k3lmfZRiDMzAsGYP98vqqVFeaw=
>>>>>>> 30d046f (slack notf)
