---
language: rust

#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

#services:
#  - docker


rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - windows
  - osx

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
    - os: windows
  include:
    - if: rust = stable OR rust = beta OR rust = nightly
      script:
        - cargo build
        - cargo doc --all-features --no-deps
        - cargo test --release
        - cargo test --release --no-default-features
        - cargo test --release --all-features

    - rust: "1.37.0"
      script:
        - cargo build --release
        - cargo build --release --no-default-features
        - cargo build --release --all-feature

          #jobs:
          #  include:
          #    - dist: bionic
          #    - dist: xenial
          #    - dist: trusty
          #    - dist: focal
