language: generic
script: echo heyo
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
after_script:
  - docker container ls
  - docker build .
  - docker stats --no-stream
  - docker pull hello-world
  - docker run -d -it --memory="5g" ubuntu
  - docker stats --no-stream
