dist: xenial
language: python
python:
- 3.7
cache:
  pip: true
  apt: true
script:
- sudo apt-get update
- python3 -u build-repo
before_install:
- openssl aes-256-cbc -K $encrypted_03b889e20542_key -iv $encrypted_03b889e20542_iv
  -in bas.txt.enc -out bas.txt -d
