language: shell
jobs:
  include:
  - stage: Tests
    if: commit_message != "Auto updating docs"
    script: echo "heyo"
  - stage: Automation
    if: commit_message = "Run automation suite"
    script: echo "hey"
dist: xenial
