sudo: required
language: shell
addon:
  artifacts: true
install: curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
deploy:
   provider: script
   script: bash artifacts
   on:
     branch: test
