---
language: generic
install: true

script:
  - python -V
  - ldd --version

jobs:
  include:
    - dist: bionic
    - dist: focal
      script:
        - pyenv install 2.7.14
        - pyenv global 2.7.14
        - python -V
