before_install:
 - wget https://imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-7.0.8-14.x86_64.rpm
 - wget https://imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-libs-7.0.8-14.x86_64.rpm
 - sudo apt-get install -y alien
 - sudo alien -d ImageMagick-7.0.8-14.x86_64.rpm
 - sudo alien -d ImageMagick-libs-7.0.8-14.x86_64.rpm
# you need the dependencies that the standard imagemagick package has
 - sudo apt-get install -y fontconfig fontconfig-config fonts-dejavu-core fonts-droid-fallback fonts-noto-mono ghostscript gsfonts hicolor-icon-theme libxt6 libavahi-client3 libavahi-common-data libavahi-common3 libcairo2 libcups2 libcupsfilters1 libcupsimage2 libdatrie1 libdjvulibre-text libdjvulibre21 libfftw3-double3 libfontconfig1 libgraphite2-3 libgs9 libgs9-common libharfbuzz0b libijs-0.35 libilmbase12 libjbig0 libjbig2dec0 libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0  libnetpbm10 libopenexr22 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpaper-utils libpaper1 libpixman-1-0 libthai-data libthai0 libtiff5 libwmf0.2-7 libxcb-render0 libxcb-shm0 libxrender1 netpbm poppler-data
# install the packages generated by alien
 - sudo dpkg -i imagemagick_7.0.8-15_amd64.deb
 - sudo dpkg -i imagemagick-libs_7.0.8-15_amd64.deb
# register libraries
 - sudo ldconfig /usr/lib64
