language: php
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
services:
  - docker
php: '7.3'
script: phpunit
jobs:
  include:
    - dist: bionic
    - dist: xenial
    - dist: trusty
