stages:
  - name: build-test-push-ecr-dev
    if: NOT branch = master
  - name: build-test-push-ecr-prd
    if: (type = pull_request) AND (branch = master)

jobs:
  include:
    - stage: build-test-push-ecr-dev
      script: echo "stage1"
    - stage: build-test-push-ecr-prd
      script: echo "stage2"
