language: shell
dist: bionic

addons:
  chrome: stable
  apt: 
    packages: 
      - postgresql-11
      - postgresql-client-11
  postgresql: "11"
before_script:
  - psql --version
  - psql -c 'create database "test_db";' 
install: true
script: echo hello
