language: bash
python:
  - "3.7"
sudo: required
dist: xenial
services:
  - docker
env:
  matrix:
    - DOCKER_COMPOSE_VERSION=1.21.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install python3 python3-pip python3-setuptools
install:
  - pip3 install --user molecule docker
  - pip3 install --user kubernetes~=9.0.0 jmespath
  - pip3 install --user ansible ansible-runner ansible-runner-http openshift 
script:
  - molecule --version
  - ansible --version
  - python3 --version
  - molecule test
  - bash ./scripts/build_and_push.sh "v0.2.0"
