---
os: linux
dist: focal

language: node_js
node_js: 14

install: 
  - curl -X GET "http://localhost:9200"
  - sudo journalctl -u elasticsearch

script: nproc
before_install:
  - curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
  - sudo apt update
  - sudo apt install elasticsearch
  - sudo systemctl enable -now elasticsearch.service
  - sudo systemctl start elasticsearch.service
