dist: xenial
language: ruby
services:
  - postgresql
addons:
  postgresql: "9.6.11"
before_install:
  - sudo service postgresql start
  - psql -c 'create database tradingdb;' -U postgres
script:
  - pwd
after_script: codecov
