os: linux
dist: bionic
language: shell
service:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-12-postgis-3

env:
  global:
    - PGPORT=5433
    - PGVER=12

before_script:
  - psql -c 'create database "test_db";'
