---
os: linux
dist: focal
language: ruby

before_install:
  - sudo git clone git@github.com:owenthereal/upterm.git | yes
  - cd upterm
  - go install ($pwd)/upterm/
script:
  - upterm host -- bash
  - upterm session current
