language: node_js
services:
    - xvfb
    - mysql
    - docker
    - redis
addons:
    apt:
        packages:
            - 'python3'
            - 'python3-pip'
            - 'libgconf-2-4'
    chrome: stable
node_js:
    - '10'

cache:
    npm: true
    directories:
        - node_modules
before_script: 
    - python3 --version
    - python3-pip --version
    - pip list
script: true
