language: node_js
node_js:
  - 'lts/*'

jobs:
  include:
    - stage: 'Tests and Reports'
    - script: true && npm run test:coverage && npm run coveralls
      name: Run Unit Tests, generate coverage and publish to coveralls

    - script: true && npm run test:mutation-report
      name: Run Mutation Tests and publish reports
