
jobs:
  include:
    - script: echo "test_1" # uses the default stage name "test"
    - script: asd.sh
    - stage: deploy
      script: skip     # usually you do not want to rerun any tests
      deploy: &script
        provider: script
        script: echo "Deployment sucessfull!!!"
