language: ruby
env:
  global:
    - TMPDIR=/tmp
rvm:
  - 2.6.6
dist: bionic
addons:
	chrome: stable
	postgresql: "11"      
before_script:
  - psql --version
  - psql -c 'create database "test_db";' 
install: true
script: echo hello
