dist: xenial

sudo  : true


services:
  - docker

before_install:
  - touch /home/travis/.docker/config.json

script:
  - sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
  - sudo chmod g+rwx "/home/$USER/.docker" -R
  - docker run -it guru:$(cat TAG) nosetests -sv

