version: ~> 1.0
language: go

os:
  - linux

cache:
  directories:
    - $GOPATH/src/gx
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

go:
  - stable

git:
  depth: 1

before_install:
  - go get -v golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

env:
  global:
    - GOFLAGS='-mod vendor'
  matrix:
    - BUILD_DEPTYPE=gomod

script: true

install: false
