---
dist: xenial
language: python
python: 3.7
virtualenv:
  system_site_packages: true

before_install: python -m pip uninstall -y pip

install:
  #- python -m pip install pip=21.3.1
  - sudo apt install python3-pip
  - sudo pip3 install --upgrade pip==21.3.1
script:
  - pip3 --version
  - pip list
