---
os: linux
dist: focal

install: true
script: true

after_success:
  - export CUR_BUILD_DIR=$(pwd)
  - echo $CUR_BUILD_DIR

###############################################################################
notifications:
  email:
    recipients:
      - mustafa@travis-ci.org
      - mustafa@travis-ci.com
