language: bash
before_install: true
install: true
stages:
  - name: Test
    if: (type IN (pull_request))
  - name: Release and Version
    if: (type IN (push) AND branch = master)


jobs:
  include:
    - stage: Test
      script: true
    - script: true
    - stage: Release and Version
      script: true
