version: ~> 1.0
language: go

os: linux

go:
  - stable

git:
  depth: 1

before_install:
  - go get -v golang.org/x/lint/golint
env:
  global:
    - GO111MODULE=on
    - GOFLAGS='-mod vendor'
  matrix:
    - BUILD_DEPTYPE=gomod

script: true
notifications:
  email: false
