language: php
    
stages:
  - test
  - functional tests
  - name: deploy
    if: branch = test
      
jobs:
    - stage: test
      env: CI_NODE_TOTAL=10 INDEX=1
      script: echo testStage
    - stage: func test
      env: CI_NODE_TOTAL=10 INDEX=1
      env: CI_NODE_TOTAL=10 INDEX=2
      env: CI_NODE_TOTAL=10 INDEX=3
      script: echo funcTestStage
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: test.sh
