jobs:
  include:
    - stage: test
      language: ruby
      rvm:
        - 2.7.5
      services:
        - postgresql
      addons:
        postgresql: "9.6"
        apt:
          update: true
          packages:
            - postgresql-client
      script: true
      cache: bundler
    - language: node_js
      node_js: 12.22.7
      env: JEST_SILENT_REPORTER_DOTS=true
      script: true
      cache: yarn
    - stage: deploy
      language: node_js
      node_js: 12.22.7
      install:
        - curl -sL https://sentry.io/get-cli/ | bash
      script: skip
      before_deploy:
        - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
      deploy:
        - provider: heroku
          api_key:
            secure: VFd5Ih8QG21vjlo44Eio9/Go443zG+0/5ENV/HDQHt8PTgl2V9iqyiXZCJEPh/8OSV1TPxZcJ0uC2OvUGOyt7IRg1Xdc8SWwNCQULCynKhgHGB+18TlgwotQVHqvxAq73MM/3IyZo71YAP1+4BultaCmG/16n61bj2BhoJ3LEy9v1DWbwtetWWtOiP6In4KPwmuyl6XPflzVH/yYoVrbxqF9koCjeaHpe8II08joyrHLFBjJ7R7DmxCJ7c+rpNOGNZnCKJaTm3+dmibIgadX/dzdm7Qc6gqbZoPos5n0ZTCeau0mJkqCI9zZyF1RS9e/UASjOf/pGPsOHL/oURGZ2+fmb0qRCJeAsjYc+3QqE4x9YGqBFDYMDJ/Tj8eEu4V+U3zTEjcm/+G63tx8UXTC8pmXzul36Is+9l06/1vCpyoqKj8eXRYbfZOqFYjfUGcz1x/orAIlOWxvZMD/PYkjw4RP7z3EJDWQFKzIEBaX5uPovN8idXe1tbKnNoqR6w74vW+i+N0tCWvQ3ZHxGq1ziwe0TlU7AGZrpofTTpFLw/BitaqToBQUMQrkOUxBwVAxYvSo8HG6JSMUj7zgNogTEZFUtsOD2k0ZmKMvO1yG9fErud3e8J/tCFAQTjIAhNoaolHvf7U7vEWbFSxqgSKMNWQtXow43lDznlAGuoYaeNA=

notifications:
  slack:
    secure: VoE5SUTQ3VkkJGyOOcpNJ4X1FyphB22Qa8Q27ZCYluhw1L02k2r/vWIsIGWe2KfStTlFupFeKqeF8QOYD8l9BxwOK6l7lDR9PUbR5paV8nD0wMs7OA8msTYXpvJH46fVdrmqVyRBFc+RE3ORw00TsHbShiNR+8zAhoEYFiwROZVsVvIBTfV4TZedYi6OW5Rg2NInf4mNX0fPKRVJTZ/euK+NIaKRticpAw0qfxK+seAyJ5UjqJ5QjMUa1lebq4vAETgk5g41ghQuhdLq1GIs7Na8+sCaQk+Yax4OxEsyy5yRmEkohxt0+cMHMKApbHl/5y2rQA6m5iJ8HliRJuWkSvTOxPeY2oQ4i8R7zY6l9y5IcYdU1M9MjfHzt0nQ6m4UUna0AWLdumGifhI+l8XtVhbHpQ2xd0oNVmOfF636JG+80WH3JJcbsOt8fwaxNeZP/HarpIB1XVrRtnVh3JaGsu3O1T6zoTZUBUwspQKK7k1Fl8sso+lCTNhoTPjgTiloOGhBFA4vBDF1U/JRdTksbXeLdx51Jx/8kyU6IXjsOU6bZLz3jZMRpQzy5TkNAO51mYnx4RoQF/QrBKSTp1OjZh+CaWUMBCzFTDqgONTbmesUD2PqbOkifaB1+0Rq9L46sNLM1YS4JZIpWNW6yg30tgjAqryI8Xu1W2Ka8153db4=
