---
language: ruby
script:
  - ruby --version
  - openssl version
install: true
services:
  - postgresql

jobs:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
      group: edge
