language: bash

stages:
  - name: test
    if: branch = master
    script: echo TEST stage
  - name: tag
    if: branch = master
    script: echo tag stage
  - name: publish
    if: branch = master
    script: echo publish stage
