language: shell
script: echo hey
deploy:
  provider: heroku
  api_key:
    secure: naGMTpPPZtASqM/r3/vUo458+92JhYrFyvyB6bz/cYDJJ67uzlyLcgTg02ndSC/qa5pRgHVJAlKVb/bgXbLOhzENf8oej0GSMPeg22CCcNh+kiYZ6/npDjWRNT99fe+xqFrD4an6L0JeHLZ7xKlQiq/XN+5lgZmsJoM6z+WbwDdoZRNYSwVkqJUwDLUUbNEo4sfYvRf9PXC8CC0/KokPsBW3R0++A3sHw+g0/uR1kZK5Hekzfu1Uio4pPA77ruvlNKLTG5jeER07PY3RRx6pkn1a0YpgNXnz/gtOAVnLzLfa4tY+9piJYDuGP9JGFGzUgSqTqXCcy8+NLRzCBOIR3XnCuYZtRvwYJD+JOw120+VxiDkz+7V902j9DA8XvQnGltqAYWj6LkykHs+XPDtuJcYvdtw6JpQenecrRFnPRSDsGCUYCh1WPQx2ldhjdZjjC5XeeD/n2VuHhuWFV5QE7PFgEaxIUOWMGP/6f0w33fpjinVMpLeWwfaNN3iG8/O7f4zdNW7rMaTm/8B5CHFGyXMrdpeCC44VbWFBt2dBhZ/NQwOyZ9fcEJurDWaSXg0mMPSFHMbNRcBo7FG1/A+OdxUvtInu81qHtWqEDxWiY1s5Aj5xTp0Pxth4fNMdF5USoNKaTxrkxvYu8NVFl5NI2trfAx/scpL9gOChsMAOkxw=
