# Note AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID env vars must be set in TravisCI externally for ECR login to work
services:
  - docker
dist: trusty

language: node_js

env:
  - NODE_ENV:production
sudo: required

node_js:
  - "8.16.1"
  - "10"
  - "node"
