---
language: generic
addons:
  rethinkdb: 2.4.1
  sonarcloud:
    organization: mustafa-travisci
    token: $SONAR_TOKEN
before_install: true
install: true
script:
  - rethinkdb -v
  - sonar-scanner --version
  - sonar-scanner
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: trusty
