addons:
  postgresql: "11"
  chrome: stable
  apt:
    update: true
    packages:
    - postgresql-11
    - postgresql-client-11
    - libwebp-dev

services:
- redis-server
- postgresql
script: true
install: skip
dist: xenial
