---
language: generic
dist: xenial
script:
  - df -h

jobs:
  include:
    - arch: amd64
    - arch: arm64-graviton2
      group: edge
      virt: lxd
    - arch: arm64-graviton2
      group: edge
      virt: vm
