language: shell
deploy:
  provider: heroku
  api_key: IeYA2jJTa6VK6r2Qkvx0k+9GnjLGszpFdiz79cuJz4ZE22cwQKkFTQ6Klpnm5vVGmHXgUWPS0jsRMKVkzdC5DPnrEankpCMi5zLP64F+9DsO6FD117A8VMMsRGsDTxxdTX4m2vbf1Q+E0dlov55yk6Vx7rmsMydvMJdNMCyUZKR6e3IxbwR6ovC4gxcQJDcUh1x/fod63X8Riqw5QSnSyzLhttN+tjTxjBWj34HX3DIpp0/uCpXBjRj22gZ5MxMGqIzhHrzCiDO+z//LI4SbfOIbx6OWTxCZHAI4JAB5uVySPE4yPJReicdkFJ+cgQBgyc8FfCaoUG4I9Nz6LOJGxnBWUPlHDgfF1lsU2/vT7mxZSqjErW6hNUclax6QRycQ2rs+8aBIzCXbPyCr5QNs7RhUhY1MDfuH0pcWmKL99QfWzIsEj4dslJbz0KYw6nGz73vUlgAVxW3bjf+VPhttK5CTMGdV8fZ943W/ZeYckWw4IhG/FaC2+Rs88vLSTa9vYquPfmknPCwFYCAaI8NrgbM8K3h9cIJju6FKlsHkE13I7+IjMqGsnuAdLednMPLLBIV0IbcINaTbb7G6DAVSLU6wAz3Z9X7d/LHAMassdqJ7bFjTfgHNHcqdnkqDIl/Rl6YPM+lzCbolfKyTT60NKlrN4Z1Kx2alIeLpKhY1Ykh4EDEM=
  app: app1
  on:
    branch: test
