---
os: linux
language: node_js
install: true
script: true
deploy:
  - provider: script
    image: ruby:latest
    script:
      - gem install dpl && gem install faraday -v 1.8.0
      - dpl --provider=heroku --app=xxx --api-key=$HEROKU_API_KEY
jobs:
  include:
    - dist: jammy
