language: generic
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
services:
  - docker
  - mysql
script: mysql -V
dist: xenial
sudo: true
group: edge
