---
os: linux
dist: focal
language: python
python: nightly
install: true
script:
  - python -V
  - openssl version

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
