os: linux
language: shell
dist: xenial

env:
  - TEST_VAR=test

script:
        - if [ env(TEST_VAR) = "test" ]; 
          then echo helloooo;
          else echo no;
          fi

after_script: true


