language: java

jdk:
  - openjdk8
  - oraclejdk8

sudo: required

if: tag IS blank # do not build tags

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: true

services:
  - docker

stages:
  - test
  - name: tag
    if: branch = master
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: tag
      language: generic
      install: false
      script: true
      deploy:
        - provider: script
          skip_cleanup: true
          script: true
    - stage: publish
      language: java
      jdk: openjdk8
      script: true
      deploy:
        - provider: script
          skip_cleanup: true
          script: true
