---
#language: generic
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

#services:
#  - docker

#jobs:
#  include:
#    - dist: bionic
#    - dist: xenial
#    - dist: trusty
#    - dist: focal
#    ---

language: android
dist: trusty
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-29.0.3
  - extra
before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
