import:
  - source: mustafa-travisci/testBuilds:common.yml@main
    mode: deep_merge_append

env:
  global:
    - deploy_qual=true;
    - config_file_public="src/js/config.json"
    - config_file_private="src/private/js/config.json"
