---
language: elixir
otp_release:
  - "25.0"
install: true
script:
  - erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
dist: focal
arch: arm64-graviton2
group: edge
virt: vm
