---
arch:
  - amd64
  - arm64
os: linux
dist: focal
language: minimal
before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential qemu-user-static xz-utils gnupg wget binfmt-support
install:
  - if ! [ -d /proc/sys/fs/binfmt_misc ]; then sudo modprobe binfmt_misc; fi
  - if ! [ -f /proc/sys/fs/binfmt_misc/register ]; then sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc; fi
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/qemu-wrapper:' | sudo tee /proc/sys/fs/binfmt_misc/register
  - sudo /etc/init.d/binfmt-support start
before_script:
  - git clone --depth 1 https://github.com/raspberrypi/tools
  - export PATH=$PATH:$PWD/tools/arm-bcm2708/arm-linux-gnueabihf/bin
script:
  - make -j$(nproc) -e QEMU_ARM=/usr/bin/qemu-arm-static CROSS_COMPILE=arm-linux-gnueabihf- all
  - make -j$(nproc) -e QEMU_ARM=/usr/bin/qemu-arm-static CROSS_COMPILE=arm-linux-gnueabihf- image
    #services:
    #- docker
    #before_install:
    #- echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

# ====> Slack notification..
notifications:
  slack:
    secure: VoE5SUTQ3VkkJGyOOcpNJ4X1FyphB22Qa8Q27ZCYluhw1L02k2r/vWIsIGWe2KfStTlFupFeKqeF8QOYD8l9BxwOK6l7lDR9PUbR5paV8nD0wMs7OA8msTYXpvJH46fVdrmqVyRBFc+RE3ORw00TsHbShiNR+8zAhoEYFiwROZVsVvIBTfV4TZedYi6OW5Rg2NInf4mNX0fPKRVJTZ/euK+NIaKRticpAw0qfxK+seAyJ5UjqJ5QjMUa1lebq4vAETgk5g41ghQuhdLq1GIs7Na8+sCaQk+Yax4OxEsyy5yRmEkohxt0+cMHMKApbHl/5y2rQA6m5iJ8HliRJuWkSvTOxPeY2oQ4i8R7zY6l9y5IcYdU1M9MjfHzt0nQ6m4UUna0AWLdumGifhI+l8XtVhbHpQ2xd0oNVmOfF636JG+80WH3JJcbsOt8fwaxNeZP/HarpIB1XVrRtnVh3JaGsu3O1T6zoTZUBUwspQKK7k1Fl8sso+lCTNhoTPjgTiloOGhBFA4vBDF1U/JRdTksbXeLdx51Jx/8kyU6IXjsOU6bZLz3jZMRpQzy5TkNAO51mYnx4RoQF/QrBKSTp1OjZh+CaWUMBCzFTDqgONTbmesUD2PqbOkifaB1+0Rq9L46sNLM1YS4JZIpWNW6yg30tgjAqryI8Xu1W2Ka8153db4=
