---
language: python
python: 3.7
dist: xenial

before_install: python -m pip uninstall -y pip

install:
  #- python -m pip install pip=21.3.1
  - sudo apt install python3-pip
  - sudo pip install --upgrade pip==21.3.1
script:
  - pip3 --version
  - pip list
