language: bash
addons:
      apt:
          sources:
            - google-chrome
before_install:
      # DISPLAY and xvfb are needed to create a virtual display into which Chrome can open
        - export DISPLAY=:99.0
        - export CHROME_BIN=chromium-browser
script: printenv
