sudo: required
dist: bionic
before_install:
 - sudo apt update
 - sudo apt build-dep imagemagick
 - wget https://www.imagemagick.org/download/ImageMagick.tar.gz
 - tar xf ImageMagick.tar.gz
 - cd ImageMagick-7*
 - ./configure
 - make
 - sudo make install
 - sudo ldconfig /usr/local/lib
 - identify -version
 - make check
scirpt: true
