language: shell

env:
  matrix:
        - CI_NODE_TOTAL=2 INDEX=2
        - CI_NODE_TOTAL=3 INDEX=3
        - CI_NODE_TOTAL=4 INDEX=4
        - CI_NODE_TOTAL=99 INDEX=99
stages:
  - test
  - Func Tests
  - Deploy

jobs:
  include:
    - stage: test
      env: 
        - CI_NODE_TOTAL=999 INDEX=999
      script: echo hello

    - stage: unit-test
      env: 
        - CI_NODE_TOTAL=9999 INDEX=9999
      script: echo hello
      
    - stage: Func Tests
      script: echo func tests

    - stage: Deploy
      env: CI_NODE_TOTAL=10 INDEX=99
      deploy:
        provider: script
        script: deploy.sh
