language: generic
script: echo hey
services:
  - docker
after_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker container ls
  - docker pull alphine
  - docker run -it --memory="6g" alphine
  - docker stats --no-stream
