language: php
sudo: required

# Needed to avoid unbuntu VM fails on Travis side
dist: xenial

addons:
  apt:
   packages:
    - mysql-server
    - mysql-client

php:
  - 7.1

sudo: true

services:
  - mysql

before_install:

  # mysql config
  # https://www.stevenrombauts.be/2018/04/custom-mysql-configuration-on-travis/
  - sudo cp .travis/mysql/mysql.cnf /etc/mysql/conf.d/
  - sudo service mysql restart

  # prepare env for travis
  - cp .travis/behat.yml behat.yml
  - cp web/.htaccess.dist web/.htaccess

install:
  - composer install --prefer-dist --optimize-autoloader --no-interaction

  # misc
  - mysql -e 'create database Mustafa_TEST;' -h 127.0.0.1 -P 3306 -u root

before_script:
  # prepare BDD (for behat)
  - sh bin/create_database.sh test

  # rabbitmq queues and exchanges creation
  - app/console travis:rabbit:install --env=test
  # NOTE : Launch only synchronous queues, as testing aynchronous ones is just useless and IN QUIET MODE
  # app/console wisembly:amqp:consume --quiet --env=test <gate name> &
  - app/console wisembly:amqp:consume --quiet --env=test --rpc survey_answer  &

  - app/console server:start 127.0.0.1:8000 --env=test --router=${TRAVIS_BUILD_DIR}/src/Wisembly/CoreBundle/Resources/config/router_test.php
