---
os: linux
dist: xenial
language: python

install: true

script: true
before_deploy:
  - TRAVIS_BUILD_NUMBER=999

deploy:
  provider: script
  script: deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BUILD_NUMBER=999
