language: php

php:
  - 7.0
  
 before_install:
  - sudo apt-get install mysql-server
  - mysql -e 'create database mmme;'
services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required
