language: bash

sudo: required

if: tag IS blank # do not build tags

script: echo main script
  
stages:
  - test
  - name: tag
    if: branch = master
    script: echo tag
  - name: publish
    if: branch = master
    script: echo pub

jobs:
  include:
    - stage: tag
      #language: generic
      #install: false
      script: echo job===>TAG
      #deploy:
        #- provider: script
          #skip_cleanup: true
          #script: echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc && git push origin "v${SDK_VERSION}"
    - stage: publish
      #language: java
      #jdk: openjdk8
      script: echo job===>PUBLISH
      #deploy:
        #- provider: script
          #skip_cleanup: true
          #script: gradle bintrayUpload
