language: node_js
node_js: "12"
env:
  - DEPLOY_DEST=staging


services:
  - docker

branches:
  only:
    - master
    - elastic-7_6_1
    - /^v[0-9].*$/

script: true

deploy:
  - provider: script
    skip_cleanup: true
    script: true
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v[0-9].*$ && $DEPLOY_DEST == staging
after_deploy:
 - echo $TRAVIS_TAG
 - echo $TRAVIS_BRANCH
