jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"
      os: osx
      script: echo Unit
    - stage: "Integrations"
      dist: xenial
      script: echo Integration
      name: "Integration Tests"     # names the second Tests stage job
    - stage: Deploy
      name: "Deploy Stage"
      deploy:
        provider: script
        script: echo Deploy
