os: windows

language: node_js

node_js:
  - 10

cache:
  - npm

before_deploy:
  - rm -rf node_modules
  - 7z a -tzip `git rev-parse HEAD`.zip * -x!.git
  - mkdir build
  - mv `git rev-parse HEAD`.zip build
