language: python

python: '3.6'

sudo: false

matrix:
  include:
    - sudo: required
      dist: trusty
      env: RELEASE=trusty
    - sudo: required
      dist: precise
      env: RELEASE=precise
    - sudo: required
      os: osx
      osx_image: xcode9.4
      env: RELEASE=precise
install:
  - true

script:
  - true
