---
os: linux
dist: focal

language: node_js

install: curl -X GET "http://localhost:9200"

script: nproc
before_install:
  - sudo echo "deb https://artifacts.elastic.co/packages/7.9.0/apt stable main" > /etc/apt/sources.list.d/elastic-7.9.0.list
  - sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
  - sudo apt-get update
  - sudo apt-get install elasticsearch
  - systemctl enable elasticsearch.service
  - systemctl start elasticsearch.service
