language: node_js
node_js: "lts/*"

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      os: osx
      osx_image: xcode7.2
      script: echo Unit
    - stage: "Tests"
      name: "Unit Tests2"
      dist: xenial
      script: echo second job in the same stage
    - stage: "Integrations"
      os: linux
      dist: xenial
      script: echo Integration
    - stage: Deploy
      name: "Deploy Stage"
      deploy:
        provider: script
        script: echo Deploy
script: echo common_scripts_here
