matrix:
  include:
    - language: php
      php: 
        - 7.4
      services:
        - redis-server
      install: true
      before_script:
        - echo '' | pecl install redis
      script:
        - composer test

    - language: python
      python: 3.6
      script: true
