language: node_js
node_js: "12"
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./build.sh deploy_staging $TRAVIS_TAG
    on:
      tags: true
      all_branches: true
      condition:$TRAVIS_TAG =~ ^v[0-9].*$ && $DEPLOY_DEST == test
