---
os: windows
language: shell
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
before_install:
  - choco install python
  - python -m pip install --upgrade pip
install: true
script: python --version
