language: shell

jobs:
  include:
  - stage: ci test
    if: branch =~ ^tes.*$
    script: true
  - stage: ci test
    if: branch =~ ^tes-.*$
    script: true
  - stage: expo export
    if: branch =~ ^tes-.*$
    script: true
  - stage: expo export2
    if: branch =~ ^tes.*$
    script: true
