sudo: required
dist: bionic
language: shell
addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-12-postgis-3
before_install:
  - psql --version
  - sudo apt-get update
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  #- sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 12
before_script:
  - psql -c 'create database travis_ci_test2;' -U postgres
