language: shell

jobs:
  include:
  - stage: ci test1
    if: branch =~ ^tes.*$
    script: true
  - stage: ci test2
    if: branch =~ ^tes-.*$
    script: true
  - stage: expo export1
    if: branch =~ ^tes-.*$
    script: true
  - stage: expo export2
    if: branch =~ ^tes.*$
    script: true
