---
_AMD64:
  arch: amd64
  os: linux
  virt: vm
_AARCH64:
  arch: arm64-graviton2
  group: edge
  os: linux
  virt: lxd
_RUBY27:
  rvm: ruby-2.7
_RUBY30:
  rvm: ruby-3.0
_RAILS61:
  gemfile: Gemfile
_TEST:
  stage: test
language: ruby
os:
  - linux
dist: focal
services:
  - redis
  - docker
addons:
  apt:
    sources:
      - sourceline: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
        key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    packages:
      - postgresql-client-13
      - postgresql-server-dev-13
      - awscli
      - python3
      - python3-pip
    update: true
env:
  global:
    - APP_NAME: "asdfasdf"
    - CC_AWS_BUCKET: "asdfasdfasdf"
    - CC_PARTS: "4"
    - PARALLEL_TEST_PROCESSORS: "4"
    - RAILS_ENV: "test"
jobs:
  include:
    - stage: test
      gemfile: Gemfile
      rvm: ruby-2.7
      arch: amd64
      os: linux
      virt: vm
      env:
        - COVERAGE: "true"
        - TEST_GROUP: "1"
    - stage: test
      gemfile: Gemfile
      rvm: ruby-2.7
      arch: amd64
      os: linux
      virt: vm
      env:
        - COVERAGE: "true"
        - TEST_GROUP: "2"
    - stage: test
      gemfile: Gemfile
      rvm: ruby-2.7
      arch: amd64
      os: linux
      virt: vm
      env:
        - COVERAGE: "true"
        - TEST_GROUP: "3"
    - stage: test
      gemfile: Gemfile
      rvm: ruby-2.7
      arch: amd64
      os: linux
      virt: vm
      env:
        - COVERAGE: "true"
        - TEST_GROUP: "4"
    - stage: test
      gemfile: Gemfile
      rvm: ruby-3.0
      arch: amd64
      os: linux
      virt: vm
      env:
        - TEST_GROUP: "1"
    - stage: test
      gemfile: Gemfile
      rvm: ruby-3.0
      arch: amd64
      os: linux
      virt: vm
      env:
        - TEST_GROUP: "2"
    - stage: test
      gemfile: Gemfile
      rvm: ruby-3.0
      arch: amd64
      os: linux
      virt: vm
      env:
        - TEST_GROUP: "3"
    - stage: test
      gemfile: Gemfile
      rvm: ruby-3.0
      arch: amd64
      os: linux
      virt: vm
      env:
        - TEST_GROUP: "4"
    - gemfile: Gemfile
      rvm: ruby-2.7
      arch: amd64
      os: linux
      virt: vm
      stage: report
      script: true
script: true

# ====> Slack notification...
notifications:
  slack:
    secure: VoE5SUTQ3VkkJGyOOcpNJ4X1FyphB22Qa8Q27ZCYluhw1L02k2r/vWIsIGWe2KfStTlFupFeKqeF8QOYD8l9BxwOK6l7lDR9PUbR5paV8nD0wMs7OA8msTYXpvJH46fVdrmqVyRBFc+RE3ORw00TsHbShiNR+8zAhoEYFiwROZVsVvIBTfV4TZedYi6OW5Rg2NInf4mNX0fPKRVJTZ/euK+NIaKRticpAw0qfxK+seAyJ5UjqJ5QjMUa1lebq4vAETgk5g41ghQuhdLq1GIs7Na8+sCaQk+Yax4OxEsyy5yRmEkohxt0+cMHMKApbHl/5y2rQA6m5iJ8HliRJuWkSvTOxPeY2oQ4i8R7zY6l9y5IcYdU1M9MjfHzt0nQ6m4UUna0AWLdumGifhI+l8XtVhbHpQ2xd0oNVmOfF636JG+80WH3JJcbsOt8fwaxNeZP/HarpIB1XVrRtnVh3JaGsu3O1T6zoTZUBUwspQKK7k1Fl8sso+lCTNhoTPjgTiloOGhBFA4vBDF1U/JRdTksbXeLdx51Jx/8kyU6IXjsOU6bZLz3jZMRpQzy5TkNAO51mYnx4RoQF/QrBKSTp1OjZh+CaWUMBCzFTDqgONTbmesUD2PqbOkifaB1+0Rq9L46sNLM1YS4JZIpWNW6yg30tgjAqryI8Xu1W2Ka8153db4=
