---
language: python

install:
  - pip3 install .

before_script:
  - pip3 install pytest

script:
  - pytest

stages:
  - name: test
    if: tag IS blank
  - name: deploy

jobs:
  include:
    - python: 3.9.7
      script: source ~/virtualenv/python3.9/bin/activate

    - python: 3.8
      script: echo "eeeee"

    - name: deploy
      script: echo "this is deploy"
