dist: trusty
language: bash
script: true

matrix:
  include:
    - language: node_js
      node_js: 10
      env:
       global:
        - 
        - APP_NAME="changED"
        - 'DEVELOPER_NAME="iPhone Distribution: ChangEd LLC (JFX9WN3DZP)"'
        - IPA_NAME="changED"
        - PROFILE_NAME="XC_iOS_comgochangedchanged"
        - ARCHIVE_NAME="changED"
