language: generic
script: echo heyo
services:
  - docker
after_script:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  - docker container ls
  - docker pull alpine
  - docker run -it --memory="6g" alpine
  - docker stats --no-stream
