os:
  - linux

sudo: false

addons:
  chrome: stable
  firefox: latest

language: node_js

node_js:
- "node" # latest
- "12"
- "10"
- "8"

cache: npm

install:
  - npm install

stages:
  - lint
  - unit tests
  - test

jobs:
  include:
    -
    - stage: 'test'
      script: echo test stage
    - stage: 'lint'
      script: echo lint stage
    - stage: 'unit tests'
      node_js: node
      script: echo unit test stage
# The script below runs using the default 'test' build stage (a.k.a. 'Test')
# in the job dashboard. The 'test' build stage uses the node_js languages 
# specified above, but the other stages & jobs need to specify the node_js 
# versions explicitly...  ¯\_(ツ)_/¯.
script: true
