dist: focal
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
      packages:
        - postgresql-12
        - postgresql-12-postgis-3
env:
  global:
  - PGUSER=postgres
  - PGPORT=5432
  - PGHOST=localhost
  - DATABASE_URL=postgres://localhost:5432/testphinternal
  - ENVIRONMENT=test
  - FORCE_DB_SETUP=true
  - PHIN_LOGGER_FORCE_CONSOLE=false
  - SKIP_CONFIG_LIST=true
script: psql -c 'create database travis_ci_test;' -U postgres
