language: ruby
install: true
script:
  - echo 'xpack.security.enabled: false' >> /usr/share/elasticsearch/config/elasticsearch.yml

services:
  - elasticsearch

before_install:
  - sudo chown -R $USER:elasticsearch /etc/default/elasticsearch
  - sudo chown -R $USER:elasticsearch /etc/elasticsearch
  - sudo service elasticsearch restart
  - curl -XGET 'http://localhost:9200'
  - "elasticsearch --version"
