---
dist: focal
language: ruby
before_install: true
install: true
script:
  - uname -a
  - lsb_release -a
deploy:
  - provider: lambda
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: "$AWS_DEFAULT_REGION"
    runtime: nodejs14.x
    edge: true
