#addons:
#    sauce_connect:
#      username: testSauce44
#      access_key: "8e18ba13-7e1d-4f78-a8aa-717f4175198b"
language: shell
script: echo script
after_script: echo hello
<<<<<<< HEAD
env:
- testvar=1234
deploy:
  provider: script
  script: cd .. && echo hello && echo world && env EC2_PUBLIC_DNS=$(testvar)
public_dns = ec2.99999999999.compute.amazonaws.com

=======
#deploy:
#  provider: script
#  script: >-
#    cd .. &&
#    echo hello &&
#    echo world
>>>>>>> 44f60164df6b198f317941a887cea888220136d0
