---
#language: generic
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

#services:
#  - docker

#jobs:
#  include:
#    - dist: bionic
#    - dist: xenial
#    - dist: trusty
#    - dist: focal
#    ---
os: linux
env:
  - TRAVIS_SCALA_VERSION: 2.13.1
  - TRAVIS_JDK: '11'
language: scala
dist: xenial
before_install:
- curl -Ls https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash
  && . ~/.jabba/jabba.sh
install:
- jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version
cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
  - "$HOME/.jabba/jdk"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
