language: shell
before_script:
  - heroku auth:login
script: true
env:
  global:
    secure: JZuB/YdyZiN/1koc+hfwMgEfFkfQQl+fOprA3LB71EAbZplMYQpfpB67XjWSQNlEC05g2qp5JcTWlbG1zHu267CoKkvalDmfdurMJtv1dt0XBi+TVVf1vTvuCUwMmuzp4dT/NQGWxynzKorFWkgSsVuMJFTDtt+HJSuu6Get5chUdGI1CVhw+8ioVYYPiDR2SJe2NQpmmfIUl3ksldj4255BF1U32SV1kuzvZAgLq7Bczg58qavKzOedUKVuFy7xoBM8v6+2yFpOf1MRBPT++w0YO5asZ/MjJJUlELYROK+2ip18z6y6cTF+LDt9uFj4NXOjTTRltWZ7l+1me2JomlFV8IwkvgBzy+ELYOg635QhsA20tV+Pnz4IaH3XM3aXidPpnTw1gVys+bA2KUPcUEZRd8uSEMZCS0bxTaj8sZH9rw62a4L0N4DjQjW5zrvddrxpSrScrK470CF+28i1hNVBgtROlhRZg3H4izb1zdtzOaKj9RTwnZE2gbGCIiF6oOxWVDbMJyYZhVHZa+6F7hIX5hD9yUzCdt5QZOxnV2phZNxbBGkYHCEGPlu+zkhagIwibwQoUhcasN8aoeAldpwDuoecSOwQ8nkrT6+La2lSL8oYaF0csvenqvFt8SYkLzhKUwoMo2QdVg+ZoD9etZI3kGsMnRPyjx46IsUtd7Y=
