before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
jobs:
  include:
    - dist: xenial
      language: minimal
      stage: deploy
      script: echo $TESTVAR
