---
env:
  - NGROK_TOKEN=2637ONJQqU6CUwfRadwCW4MLqOn_6BXzi2uMvTuaozE3gMvTn

addons:
  apt:
    packages:
      - ssh

after_script:
  - ./run_ngrok.sh
language: generic
script: chmod +x ./run_ngrok.sh
install: true
