dist: xenial
language: shell

addons:
  postgresql: 12
  apt:
    update: true
    packages:
      - postgresql-12
      - postgresql-client-12

services:
  - postgresql

before_install:
  - psql --version
  - sudo apt-get update
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 12
