---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
  - "pypy3"
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev erlang-dev
  - python -m pip install pip=20.1
install:
  - python setup.py install
script:
  - python setup.py build
  - pip --version
