language: python
python:
  - "3.6"
os: windows

# command to run tests

  
services:
  - docker


before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
  - pytest
