os: linux
dist: xenial
language: java
# Run the integration test with 'verify'
script: ./mvnw clean verify
# Speed up the build by caching maven dependencies.
cache:
  directories:
  - .autoconf
  - $HOME/.m2
