osx_image: xcode10.2
sudo: required
language: c
script: true
jobs:
  include:
    stage:
      - name: a
        script: true
    stage:
      - name: b
        script: true
    stage:
      - name: c
        script: true
