language: php
addons:
  apt:
    packages:
    - python-pip
php:
- "7.3"
dist: bionic
sudo: required
services:
- mysql
- docker
cache:
  directories:
  - $CACHE_DOCKER
  - $CACHE_PIP
  - vendor
  - node_modules
  - $CACHE_COMPOSER
