os:
- linux #creates a 1st job that defaults the language: ruby
- osx #creates a 2nd job that defaults the language: ruby


dist: bionic
jobs:
  include:
    -  
      language: minimal
      name: Bash test
      install:
        - ./bash/test/shunit2Install.sh
        - ./install.sh softHSM
    - 
      language: node_js 
      name: Second testi
      install: true
