---
language: python
python: 3.7
script:
  - python -V
  - pip --version
before_install:
  - pip --version
  - python -m pip install pip==20.1
install: true

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
      group: edge
