language: generic
before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
services:
  - docker
script: true


dist: xenial

addons:
  postgresql: 11
  apt:
    update: true
    packages:
      - postgresql-11
      - postgresql-client-11
before_install:
  - postgres --version
  - sudo apt-get update
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo service postgresql stop
  - sudo service postgresql start 11
before_script:
  - psql -c 'create database travis_ci_test2;' -U postgres
after_script:
  - postgres --version
