---
#language: generic
#before_install:
#  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

#services:
#  - docker

#jobs:
#  include:
#    - dist: bionic
#    - dist: xenial
#    - dist: trusty
#    - dist: focal
#    ---
language: objective-c
os:
- osx
osx_image:
- xcode12.4
rvm:
- 2.7.2
go:
- '1.16'
install: true
script:
  - brew install swift-protobuf grpc
  - brew cask install ugroupmedia/pnp/grpc-java
  - brew install ugroupmedia/pnp/php-grpc ugroupmedia/pnp/grpc-swift ugroupmedia/pnp/grpc-web
