---
dist: xenial
allow_failure:
  - rvm: 2.5.3
jobs:
  include:
    - stage: warm_cache

      script:
        - echo $TRAVIS_TEST_RESULT >> test.sh
      workspaces:
        create:
          name: ws1
          paths:
            - test.sh
    - stage: warm_cache2_fail
      rvm: 2.5.3
      script:
        - cmake 22222
        - sed '$s/$/"$TRAVIS_TEST_RESULT"' test.sh
      workspaces:
        create:
          name: ws1
          paths:
            - test.sh
    - stage: use_cache
      workspaces:
        use: ws1
      script:
        - cat test.sh || true
