#addons:
#    sauce_connect:
#      username: testSauce44
#      access_key: "8e18ba13-7e1d-4f78-a8aa-717f4175198b"
language: shell
script: echo script
after_script: echo hello
env:
  - testvar=1234
deploy:
  provider: script
  script: >-
    cd .. &&
    echo hello &&
    echo world &&
    export $EPD=testvar &&
    echo $EPD
