---
os: linux
language: generic
install: true
dist: focal
script: true
git:
  clone: false

before_install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git --branch test --single-branch $TRAVIS_REPO_SLUG
  - git fetch --unshallow
  - git tag
  - cd $TRAVIS_REPO_SLUG && ls -all
