language: ruby
install: true

script: true

services:
  - elasticsearch
  - postgresql

before_install:
  - sudo chown -R $USER:elasticsearch /etc/default/elasticsearch
  - sudo chown -R $USER:elasticsearch /etc/elasticsearch
  - sudo service elasticsearch restart
  - curl -XGET 'http://localhost:9200'
  - "elasticsearch --version"
