---
os: linux
virt: lxd
arch: arm64-graviton2
group: edge
language: cpp
compiler: gcc
script: true
install: skip

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
