language: shell
os:
- linux
dist: bionic
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6
    - postgresql-server-dev-9.6
    - postgresql-common
services:
- redis
before_install:
  - psql --version
